apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: LoadBalancer
  selector:
    app: vehicle-rental-spring-boot-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
